[LIT-8] Implemented refund feature for resell flow.
mygento/kkm pull request #63
Opened 2020-09-23 13:22 UTC by Mavlyan

2020-12-21 12:08 UTC, luckyraul requested changes

2020-12-21 12:08 UTC, luckyraul commented on Controller/Adminhtml/Cheque/Resell.php
> +                $comment = $this->kkmHelper->isMessageQueueEnabled()
sync/async

2020-12-21 12:08 UTC, luckyraul commented on Helper/Resell.php
> +        //TODO: Test this case
todo ?

2020-12-21 12:08 UTC, luckyraul commented on Helper/TransactionAttempt.php
> +            return $attempt;
why?

2020-12-21 12:08 UTC, luckyraul commented on Model/Processor/Send.php
> +    protected $helper;
private?

2020-12-21 12:08 UTC, luckyraul commented on Model/Processor/Update.php
> +    protected $vendor;
private

2021-01-12 13:48 UTC, Mavlyan commented on Helper/TransactionAttempt.php
> +            return $attempt;
а пёс его знает...

2021-02-11 11:55 UTC, luckyraul approved these changes

2021-02-11 11:55 UTC, merged