Добавлена интеграция с ЧекОнлайн (ASUS-3)
mygento/kkm pull request #72
Opened 2021-04-27 07:33 UTC by odahviiiing

2021-07-05 12:33 UTC, Mavlyan requested changes

2021-07-05 12:33 UTC, Mavlyan commented on Api/Data/ItemInterface.php
> +     * @return float|int
![image](https://user-images.githubusercontent.com/8666986/124127390-54e89900-da84-11eb-94eb-b4b4ed1e9eff.png)

если уж править типы - то и строку тож надо учитывать

2021-07-05 12:33 UTC, Mavlyan commented on Api/Data/ItemInterface.php
> +     * @return float|int
такая же история как и в пред каменте

2021-07-05 12:33 UTC, Mavlyan commented on Api/Processor/SendInterface.php
> +    public function proceedCommonResell($invoice, $sync = false, $ignoreTrials = false, $incrExtId = false);
чот не оч круто иметь в интерфейсе методы, которые не универсальны, а в каких-то вендорах остаются заглушками. по сути этот интерфейс надо реформировать. но тут надо обсудить.

2021-07-05 12:33 UTC, Mavlyan commented on Helper/Request.php
> +    public function isGiftCard($salesEntity, $itemName)
чот этот хелпер прям реально в мусорку превратился. раз уж мы идём путём хелперов - давай хотя бы разделять их по задачам. некое жалкое подобие SingleResponsibility.
* Методы, относящиеся к кодированию маркировок - логично вынести в отдельный хелпер.
* Методы, относящиеся к подарочной карте и кредитам - в еще отдельный (типа isGiftCard) Но в идеале - иметь некий класс RequestBuilder и, возможно, абстрактный класс этого же билдера, который будет содержать общие методы и проверки.

2021-07-05 12:33 UTC, Mavlyan commented on Helper/OrderComment.php
> +        if ($response->getStatus() == Response::STATUS_DONE
такие ацкие кондишны лучше выносить в отд метод. сделай плз

2021-07-05 12:33 UTC, Mavlyan commented on Helper/OrderComment.php
> +        } else {
стандартная тема: если где-то появляется else - там просится еще один метод. декомпозируй плз

2021-07-05 12:33 UTC, Mavlyan commented on Model/Atol/Vendor.php
> +        $this->orderCommentHelper->addCommentToOrder($entity, $response, $txnId, $operation);
Не вижу смысла в этом методе addCommentToOrder, который был вынесен в интерфейс. Его снаружи всё равно никто не использует. 
Поэтому в этом вендоре и в новом вендоре предлагаю напрямую юзать комент из OrderComment Hellpera. А метод дропнуть к свиням из интерфейса и классов.

2021-07-05 12:33 UTC, Mavlyan commented on Model/Atol/Vendor.php
> +    public function isNeedUpdateStatus()
смешной метод получился) с первого взгляда хочется переименовать в `public function getTrue() { return true;}` )))

А если серьезно - я бы его вынес в интерфейс - т.к. он используется снаружи. Ну и написал бы док к нему, потому что он ваще неочевидный. С первого взгляда похоже на какую-то шляпу, которую случайно забыли

2021-07-05 12:33 UTC, Mavlyan commented on Model/CheckOnline/Client.php
> +                $configPath = $isTestMode ? 'checkonline/test_cert' : 'checkonline/cert';
строки с путями к конфигам стоит вынести в класс конфига и сделать константами.
но лучше сделать методы getЧекОнлайнCert например. Он там сам себе разберется в каком режиме он работает и какой тебе вернуть - для тестовой среды или прод.

2021-07-05 12:33 UTC, Mavlyan commented on Model/CheckOnline/Client.php
> +        $filePathInVar = self::CERT_STORAGE_DIR[$mode] . '/' . $this->kkmHelper->getConfig($configPath, $storeId);
какая-то сложная история с $mode. Почему не сделат ь 2 разные строковые константы вместо одной с массивом и тогда


$path = $isTestMode ? self::TEST_CERT_STORAGE_DIR: self::PROD_CERT_STORAGE_DIR;

2021-07-05 12:33 UTC, Mavlyan commented on Model/CheckOnline/Client.php
> +     * @param \Mygento\Kkm\Helper\Data $kkmHelper
кол-во параметров в доке не соотв кол-ву пар-ров метода

2021-07-05 12:33 UTC, Mavlyan commented on Model/CheckOnline/Client.php
> +        if (!$this->file->isFile($fileAbsolutePath) || !$this->file->isExists($fileAbsolutePath)) {
isExists тебе и так выбросит эксепшн. Похоже, что с каким-то не очень вразумительным ответом. Но это надо проверить:

![image](https://user-images.githubusercontent.com/8666986/124255797-3d1c1e00-db33-11eb-91c5-d740abd78784.png)

2021-07-05 12:33 UTC, Mavlyan commented on Model/CheckOnline/Client.php
> +            ? 'checkonline/test_api_url' : 'checkonline/api_url';
всё в конфиг, всё в конфиг. Никаких строковых значений в классе клиента.

Еще такой момент: у тебя 2 разных метода : isTestMode (для АТОЛа) и isCheckonlineTestMode (для чеконлайна). 
странная история. думаю, что надо чтобы модуль ККМ работал в тестовом режиме, а не конкретный вендор.

2021-07-05 12:33 UTC, Mavlyan commented on Model/CheckOnline/Client.php
> +            throw new VendorBadServerAnswerException(
а почему б не заюзать Мажентовский Json класс - он бросает :hankey:  эксепшны

2021-07-05 12:33 UTC, Mavlyan commented on Model/CheckOnline/Item.php
> +    const PAYMENT_METHOD_FULL_PAYMENT = 4;
модификаторы доступа к константам. Других мест тоже касается.
Вообще рекомендую на шторм поставить вот такой плагин и выставылять версию РНР в шторме
![image](https://user-images.githubusercontent.com/8666986/124471791-faae4780-dda5-11eb-8a72-9e0c394141aa.png)

этот плагин будет подсвечивать такие штуки.

2021-07-08 07:46 UTC, odahviiiing commented on Api/Processor/SendInterface.php
> +    public function proceedCommonResell($invoice, $sync = false, $ignoreTrials = false, $incrExtId = false);
Переименовал метод в интерфейсе и сделал соответствующие изменения в имплементации.

2021-07-08 07:47 UTC, odahviiiing commented on Helper/Request.php
> +    public function isGiftCard($salesEntity, $itemName)
Сделал абстрактный класс билдера, все методы связанные с формированием запроса вынес туда.

2021-07-08 07:47 UTC, odahviiiing commented on Helper/OrderComment.php
> +        if ($response->getStatus() == Response::STATUS_DONE
сделал

2021-07-08 07:47 UTC, odahviiiing commented on Helper/OrderComment.php
> +        } else {
сделал

2021-07-08 07:48 UTC, odahviiiing commented on Model/Atol/Vendor.php
> +        $this->orderCommentHelper->addCommentToOrder($entity, $response, $txnId, $operation);
Убрал метод addCommentToOrder из интерфейса и классов вендоров.

2021-07-08 07:49 UTC, odahviiiing commented on Model/Atol/Vendor.php
> +    public function isNeedUpdateStatus()
Убрал этот метод. Добавил интерфейс StatusUpdatable, туда вынес метод updateStatus()

2021-07-08 07:50 UTC, odahviiiing commented on Model/CheckOnline/Client.php
> +        $filePathInVar = self::CERT_STORAGE_DIR[$mode] . '/' . $this->kkmHelper->getConfig($configPath, $storeId);
Сделал через 2 константы вместо массива.

2021-07-08 07:50 UTC, odahviiiing commented on Model/CheckOnline/Client.php
> +     * @param \Mygento\Kkm\Helper\Data $kkmHelper
поправил

2021-07-08 07:51 UTC, odahviiiing commented on Model/CheckOnline/Client.php
> +        if (!$this->file->isFile($fileAbsolutePath) || !$this->file->isExists($fileAbsolutePath)) {
Метод isExists() не бросает исключение когда файла не существует. А мне нужно исключение когда файла нет. Так более информативный лог получается.

2021-07-08 07:51 UTC, odahviiiing commented on Model/CheckOnline/Client.php
> +            ? 'checkonline/test_api_url' : 'checkonline/api_url';
сделал.

2021-07-08 07:52 UTC, odahviiiing commented on Model/CheckOnline/Client.php
> +            throw new VendorBadServerAnswerException(
Убрал этот метод. Использую параметр JSON_THROW_ON_ERROR.

2021-07-08 07:52 UTC, odahviiiing commented on Model/CheckOnline/Item.php
> +    const PAYMENT_METHOD_FULL_PAYMENT = 4;
поправил.

2021-07-08 07:55 UTC, odahviiiing commented on Api/Data/ItemInterface.php
> +     * @return float|int
Для api метод `getPrice()` и `getQuantity()` не должны возвращать строки, иначе сервис вернет ошибку. Поэтому, я считаю, тут не нужно тип `string` в качестве возможного возвращаемого типа.

2021-07-08 07:57 UTC, odahviiiing commented on Api/Data/ItemInterface.php
> +     * @return float|int
Аналогично ответу к предыдущему комментарию

2021-09-15 08:44 UTC, odahviiiing commented on Model/CheckOnline/Client.php
> +                $configPath = $isTestMode ? 'checkonline/test_cert' : 'checkonline/cert';
сделал

2021-09-24 09:59 UTC, Mavlyan commented on Api/Queue/ConsumerProcessorInterface.php
> +    public function processSell($queueMessage);
предлагаю типы данных указать и принимаемых и возвращаемых. 
и в интерфейсе и в, соответственно, реализациях

2021-09-24 09:59 UTC, Mavlyan commented on Model/Queue/Consumer/CheckOnline/ConsumerProcessor.php
> + * Class ConsumerProcessor
капитанские комментарии

2021-09-24 09:59 UTC, Mavlyan commented on Model/Queue/Consumer/CheckOnline/ConsumerProcessor.php
> +     * @var \Mygento\Kkm\Helper\Error\Proxy
Proxy надо сетить через di.xml.
А здесь - зависимость от конкретного класса, а не его проксей, фасадов и прочих надстроек

![image](https://user-images.githubusercontent.com/8666986/134489629-ad2f0a7e-693d-496c-9947-bc6725713c28.png)

2021-09-24 09:59 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            if ($queueMessage->getOperationType() === RequestInterface::RESELL_SELL_OPERATION_TYPE) {
тут шото не то происходит. Если это operationType RESELL, то почему при отлавливании эксепшнов мы отправляем в топик SELL ? 

в классах-консьюмерах для АТОЛ всё было прозначно. Таких проверок не было

2021-09-24 09:59 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +<?php
предлагаю архитектурное улучшение:
* ConsumerProcessor чтобы не объединял в себе все методы, а работал только как прокси к классам, где происходят атомарные операции. максимум - собирал из queueMessage объект реквеста и проксировал внутрь атомарного класса объект реквеста. 

Таким образом классы-консьюмеры АТОЛа переедут в папку АТОЛ без изменений и, мне кажется, будет легче ревьювить и мы избежим непреднамеренных ошибок в логике

2021-09-24 09:59 UTC, Mavlyan commented on Api/Queue/QueueMessageInterface.php
> +    public function setOperationType($operationType): QueueMessageInterface;
можно указать `int` как принимаемый тип и метод будет самодокументируемым. phpDoc не нужен

2021-09-24 09:59 UTC, Mavlyan commented on Api/Queue/ConsumerProcessorInterface.php
> +<?php
grump проверь. 
ККМ 2.3 зелёный, твоя версия - красная.

2021-09-24 09:59 UTC, Mavlyan commented on Console/SendRefund.php
> +            if ($status != Response::STATUS_DONE && $status != Response::STATUS_WAIT) {
👍

2021-09-24 09:59 UTC, Mavlyan commented on Console/UpdateStatus.php
> +     * @param $storeId
каков тип параметра? 
можно типы данных традиционно указать в сигнатуре

2021-09-24 09:59 UTC, Mavlyan commented on Controller/Frontend/Callback.php
> +            $vendor = $this->kkmHelper->getCurrentVendor($this->storeManager->getStore()->getId());
я бы делал вендорную фабрику зависимой от Data хелпера. А то +1 ответственность для и так бестолкового хелпера.
Но это мысли вслух, переделывать не нужно

2021-09-24 09:59 UTC, Mavlyan commented on Crontab/ProceedScheduledAttempt.php
> +        \Magento\Store\Model\StoreManagerInterface $storeManager
остальные классы через USE подключены. 
Этот тоже стоит так подключить чтобы красиво было)

2021-09-24 09:59 UTC, Mavlyan commented on Crontab/ProceedScheduledAttempt.php
> +                $this->kkmHelper->critical($e);
трейс эксепшна тоже пишется в лог?

2021-09-24 09:59 UTC, Mavlyan commented on Helper/Data.php
> +        $this->vendorFactory = $vendorFactory;
Паша, оцени плиз - насколько долго фабрику сделать зависимой от хелпера, а не наоборот. А то появление этого бестолкового по большому счету конструктора печалит

2021-09-24 09:59 UTC, Mavlyan commented on Helper/Data.php
> +    public function isVendorNeedUpdateStatus($storeId = null)
возвращаемый тип

2021-09-24 09:59 UTC, Mavlyan commented on Helper/OrderComment.php
> +     */
типы данных и лишний РНР док

2021-09-24 09:59 UTC, Mavlyan commented on Model/CheckOnline/RequestBuilder.php
> +        if (!isset($item['tax']) || $item['tax'] === null) {
`!($item['tax'] ?? false)`  - не то же ли самое? 

я такие штуки вообщ люблю выносить в переменные или отдельные методы

isTaxValid = (bool) ( $item['tax'] ?? false );
if (isTaxValid) {
 ... blahblahblah 


Так читается и пишется проще. Иначе моск закипает на N-ном условии

2021-09-24 09:59 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            if ($queueMessage->getOperationType() === RequestInterface::RESELL_SELL_OPERATION_TYPE) {
Проверь плиз топики в других методах

2021-09-24 09:59 UTC, Mavlyan commented on Model/Queue/Consumer/CheckOnline/ConsumerProcessor.php
> +                $this->attemptHelper->scheduleNextAttempt($request, SendInterface::TOPIC_NAME_RESELL);
насколько я знаю в 100% случаев, когда есть else {} - то он не нужен. Решается либо вынесением в отдельный метод либо - как в нашем случае можно сделать просто return внутри ифа.

и еще - при обработке этих эксепшнов точно должно быть сообщение `info` в логах? или всё-таки warning||error?

2021-09-24 09:59 UTC, Mavlyan commented on Model/Request/AbstractRequestBuilder.php
> +     * AbstractRequestBuilder constructor.
капитанские комментарии щас не в тренде)

2021-09-24 09:59 UTC, Mavlyan commented on Model/Request/AbstractRequestBuilder.php
> +    protected function normalizeHex(string $hex): string
яб вынес методы работы с маркировками в какой-то класс, типа хелпера по маркировкам.

2021-09-24 09:59 UTC, Mavlyan commented on Model/Source/Sno.php
> +    // phpcs:disable
1. этот интерфейс депрекейтед. Раз уж делаешь изменения в этом файле - то можно заменить на OptionSourceInterface.
2. Если уж делаешь сурс модель для чек онлайна, то красиво было бы сделать и для АТОЛа. 
типа - один интерфейс с методами getOsnCode, getUsnIncomeCode(), etc.  
Реализации живут в разных папках и тянутся в system.xml в каждом месте своя.

2021-10-06 08:18 UTC, odahviiiing commented on Model/CheckOnline/RequestBuilder.php
> +        if (!isset($item['tax']) || $item['tax'] === null) {
упростил до `!isset($item['tax'])` т.к. isset итак проверяет на null.

2021-10-06 08:33 UTC, odahviiiing commented on Model/Request/AbstractRequestBuilder.php
> +    protected function normalizeHex(string $hex): string
Не уверен что это обязательно, т.к. эти методы относятся только к построению запроса и нигде больше не используются. Так ли необходимо делать еще один хелпер ради двух методов?

2021-10-06 08:41 UTC, odahviiiing commented on Model/Source/Sno.php
> +    // phpcs:disable
По 2-му пункту не совсем понимаю что имеется в виду. Не будет ли использование интерфейса излишним усложнением?

2021-10-06 16:54 UTC, odahviiiing commented on Crontab/ProceedScheduledAttempt.php
> +                $this->kkmHelper->critical($e);
Да, при такой записи трейс пишется.

2021-10-06 21:50 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            if ($queueMessage->getOperationType() === RequestInterface::RESELL_SELL_OPERATION_TYPE) {
Тут не просто RESELL, а RESELL_SELL. что по сути является SELL, только externalId имеет вид `invoice_1_000012_resell`. Поэтому и отправляем в топик SELL.
Эта проверка необходима для построения нужного запроса, т.к. мы изменили сообщение для топика. 
Раньше сообщение из себя представляло запрос целиком, в котором поле `externalId` принимало корректное значение (invoice_1_000012_resell) для выполнения операции resell_sell следующей за refund. Сейчас же в сообщении только entityId, storeId, operationType. И без проверrb будет билдиться запрос на операцию sell когда на самом деле нужен запрос для операции resell_sell.

2021-10-06 23:29 UTC, odahviiiing commented on Helper/Data.php
> +        $this->vendorFactory = $vendorFactory;
К сожалению такое сделать будет затруднительно из-за метода isVendorNeedUpdateStatus(), которому нужен инстанс текущего вендора и зависимость в хелпере все равно останется. Так ли плох этот конструктор? Он же, по сути, ничего плохого из себя не представляет.

2021-10-06 23:45 UTC, odahviiiing commented on Api/Queue/QueueMessageInterface.php
> +    public function setOperationType($operationType): QueueMessageInterface;
Без phpDoc будет валиться компиляция. Добавил тип параметра и оставил phpDoc

2021-10-06 23:46 UTC, odahviiiing commented on Controller/Frontend/Callback.php
> +            $vendor = $this->kkmHelper->getCurrentVendor($this->storeManager->getStore()->getId());
Будет затруднительно из-за метода `isVendorNeedUpdateStatus()`

2021-10-06 23:46 UTC, odahviiiing commented on Model/Source/Sno.php
> +    // phpcs:disable
сделал через абстрактный класс

2021-10-07 00:00 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +<?php
сделал.

2021-10-27 10:11 UTC, Mavlyan requested changes

2021-10-27 10:11 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->helper->critical($e->getMessage());
я вот тут задумался - а не заруинилась ли обработка ошибок? 
Раньше метод buildRequest был внутри try-catch. И если в нём происходил Exception (хз насколько это реально, надо смотреть), то эта ошибка тоже руинила отправку и планировал отправку на следующий раз. 
Сейчас стало: если происходит ошибка в buildRequest, то мы пишем в лог Критическую ошибку и не планируем следующую отправку.

2021-10-27 10:11 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->helper->critical($e->getMessage());
Что-то похожее, что и в пред.методе

2021-10-27 10:11 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->helper->critical($e->getMessage());
+1

2021-10-27 10:11 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/AtolUpdateConsumer.php
> +     * @throws \Exception
он не бросает Эксепшнов, у тебя они все перехвачены

2021-10-27 10:11 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->updateConsumer->sendUpdateRequest($updateRequest);
Этот консьюмер не бросает ошибок, судя по его коду. Оборачивать бессмысленно

2021-10-27 10:11 UTC, Mavlyan commented on Model/Source/Atol/Sno.php
> +    protected $osnValue = self::RECEIPT_SNO_OSN;
тут тоже интересный момэнт:

зачем нам нужны защищенные свойства, если можно заюзать защищенные константы и позднее статическое связывание? 

```
abstract class A {
    public function ec() {
        echo static::OO; // Вот супер фича!
    }
    
}


class B extends A {
    protected const OO = 1;

}

$b = new B();

$b->ec();
```

2021-10-29 07:40 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/AtolUpdateConsumer.php
> +     * @throws \Exception
`$this->requestHelper->getEntityByUpdateRequest($updateRequest)` может бросить исключение.

2021-10-29 08:04 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->updateConsumer->sendUpdateRequest($updateRequest);
Там есть неперехваченное исключение
`$this->requestHelper->getEntityByUpdateRequest($updateRequest)`

2021-11-01 16:02 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->helper->critical($e->getMessage());
Добавил планирование отправки на следующий раз.

2021-11-01 16:02 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->helper->critical($e->getMessage());
поправил

2021-11-01 16:02 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->helper->critical($e->getMessage());
поправил

2021-11-01 16:03 UTC, odahviiiing commented on Model/Source/Atol/Sno.php
> +    protected $osnValue = self::RECEIPT_SNO_OSN;
заюзал позднее статическое связывание

2021-11-08 10:58 UTC, Mavlyan commented on Model/Atol/Vendor.php
> +
а что будет если вывалится, например, `VendorNonFatalErrorException` ?
Не заруинится ли крон процесс или вызов этого метода из контроллера?

2021-11-08 11:06 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            if (!isset($request)) {
выброс эксепшына можно добавить в блок default свича. Дескать, если уж мы дошли до default - значит точно какой-то неведомый тип операции прилетел. 

И кстати, имхо, `break` лучше не опускать, даже если он не нужен: когда надо будет добавить новый кейс для свича - будет всегда искушение скопировать предыдущий. А в нём нет break. И может случиться неопознанная летающая шляпа.

2021-11-08 11:06 UTC, Mavlyan commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->sellConsumer->sendSellRequest($request);
я ошибаюс или sellConsumer сам тоже перехватывает \Throwable? В этом случае здесь бессмысленно  оборачивать в try-catch

2021-11-10 02:23 UTC, odahviiiing commented on Model/Atol/Vendor.php
> +
Это предотвращает создание новых транзакций в Мадженто в случае ошибки когда uuid не возвращается в ответе. Если вывалится `VendorNonFatalErrorException` то этот код не выполнится, т.к. тут ловится только `CreateDocumentFailedException`

2021-11-10 02:43 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            $this->sellConsumer->sendSellRequest($request);
Исключение может выбросить `buildRequestForResellSell` или `buildRequest`. Это доработка к одному из прошлых тових комментов https://github.com/mygento/kkm/pull/72#discussion_r737304673

2021-11-10 02:53 UTC, odahviiiing commented on Model/Queue/Consumer/Atol/ConsumerProcessor.php
> +            if (!isset($request)) {
Перенес выброс исключения в блок default.

2021-11-10 09:41 UTC, Mavlyan approved these changes

2021-11-19 11:06 UTC, luckyraul commented on Model/Source/Vendors.php
> +    const ATOL_VENDOR_CODE = 'atol';
const visibility

2021-11-25 11:05 UTC, merged