[SS-1178] Send to KKM with incr ext id
mygento/kkm pull request #74
Opened 2021-05-26 07:11 UTC by Hector68

2021-05-26 10:09 UTC, Mavlyan commented on Plugin/ExtraSalesViewToolbarButtons.php
> +        return false === empty($transactions) &&
А что это за условие? Если я правильно понимаю - зафейленные транзакции могут быть. Поэтому с этим условием мы не сможем переотправить их

2021-05-26 10:15 UTC, Hector68 commented on Plugin/ExtraSalesViewToolbarButtons.php
> +        return false === empty($transactions) &&
Ну условие как раз, если до этого была хоть одна транзакция, то показываем кнопку. Если до этого не было вообще транзакций, то кнопку не показываем.

2021-05-26 13:14 UTC, luckyraul requested changes

2021-05-26 13:14 UTC, luckyraul commented on Plugin/ExtraSalesViewToolbarButtons.php
> +        if ($this->canBeShownResendWithIncrExtIdButton($transactions)) {
isVisible phrase much better

2021-05-26 13:44 UTC, Hector68 commented on Plugin/ExtraSalesViewToolbarButtons.php
> +        if ($this->canBeShownResendWithIncrExtIdButton($transactions)) {
done

2021-05-27 14:33 UTC, luckyraul commented on Plugin/ExtraSalesViewToolbarButtons.php
> +            $buttonList->add('resend_to_kkm', $data);
duplicate button id

2021-05-27 14:48 UTC, merged