[LIT-99] Add store id as argument for config methods
mygento/kkm pull request #76
Opened 2021-06-21 11:22 UTC by alextorini

2021-06-22 14:22 UTC, Mavlyan requested changes

2021-06-22 14:22 UTC, Mavlyan commented on Console/UpdateStatus.php
> +            $uuids = [$param];
если появляется else - значит нужно вынести в отдельный метод.

2021-06-22 14:22 UTC, Mavlyan commented on Console/UpdateStatus.php
> +            $uuids = [$param];
а, да! и у тебя все uuidы не мержаться, а перетираются. Приходит новый стор, выдаёт новую пачку юидов - она затирает предыдущую пачку.

2021-06-22 14:22 UTC, Mavlyan commented on Console/UpdateStatus.php
> +            $uuids = [$param];
для апдейта как берутся настройки стора? 
мы же не знаем какому стору принадлежит какой юид

2021-06-22 14:22 UTC, Mavlyan commented on Crontab/Update.php
> +                        $response = $this->updateProcessor->proceedSync($uuid);
тот же вопрос - как при апдейте становится известно для какого стора мы получаем токен и какой groupCode используем в урле для апдейта?

2021-06-22 14:22 UTC, Mavlyan commented on Crontab/Update.php
> +            $this->kkmHelper->debug('Publish request: ', $uuid->toArray());
![image](https://user-images.githubusercontent.com/8666986/122930676-db122a80-d374-11eb-808d-ae8cfc159146.png)

Karaul!

2021-06-22 14:22 UTC, Mavlyan commented on Crontab/Update.php
> +        if ($uuid instanceof DataObject) {
а чо ДатаОбжект, а не конкретный интерфейс?

2021-06-22 14:22 UTC, Mavlyan commented on Helper/Data.php
> +        return parent::getConfig($this->getCode() . '/' . $param, $scopeCode) ?? '';
лучше тогда уже преобразование к строке использовать (string) parent::getConf....

2021-06-22 14:22 UTC, Mavlyan commented on Helper/Data.php
> +    public function getStoreEmail($storeId = null): ?string
null не вернет, ты ж изменил метод гетКонфиг

2021-06-22 14:22 UTC, Mavlyan commented on Helper/Data.php
> +    public function getConfig($param, $scopeCode = null): string
я бы не стал к строке преобразовывать. а то надо менять много мест, где проверка на нулл. и как будут возвращаться integer значения, вдруг где-то кто-то 3 знака = использует

2021-06-25 15:09 UTC, Mavlyan requested changes

2021-06-25 15:09 UTC, Mavlyan commented on Console/UpdateStatus.php
> +                foreach ($uuids as $uuid) {
пока вопрос у меня остается: каким образом классы апдейтеры узнают про стор из которого надо брать креды АТОЛа? к ним же прилетает просто строка

2021-06-25 15:09 UTC, Mavlyan commented on Crontab/Update.php
> +        if ($updateRequest instanceof UpdateRequestInterface) {
а зачем проверка, если тремя строками выше фабрика строго возвращает объект этого типа ?

2021-06-25 15:09 UTC, Mavlyan commented on Helper/Data.php
> +     * @param null $scopeCode
а строка или инт не может прийти? :)

2021-06-25 15:09 UTC, Mavlyan commented on Helper/Request.php
> +     *@throws \Exception
grumphp не проверял?

2021-06-25 15:09 UTC, Mavlyan commented on Helper/Transaction.php
> +                ))
уверен, что условие вот такое `sales_order.entity_id = @storeId` ?

2021-06-25 15:09 UTC, Mavlyan commented on Helper/Transaction.php
> +                    '%s.%s IS NULL',
может IS NOT NULL ? 
нужен твой комментарий, не оч понимаю что тут происходит

2021-06-25 15:09 UTC, Mavlyan commented on Helper/TransactionAttempt.php
> +     *@throws \Magento\Framework\Exception\NoSuchEntityException
grumphp

2021-06-25 15:09 UTC, Mavlyan commented on Helper/TransactionAttempt.php
> +        string $scheduledAt = null
?string

2021-06-25 15:09 UTC, Mavlyan commented on Helper/TransactionAttempt.php
> +        $storeId = $this->orderRepository->get($attempt->getOrderId())->getStoreId();
получение ордера достаточно дорогая операция. Этот метод вызывается в другом, который содержит RequestInterface. Мы можем из RequestInterface получить storeId ?

2021-06-25 15:09 UTC, Mavlyan commented on Model/Atol/Client.php
> +    protected function getBaseUrl(?int $storeId = null): string
а строкой может прийти storeId ? 
Вообще в целом впечатление, что надо навести порядок с параметром storeId - какого он типа и какой у него phpDoc

2021-06-25 15:09 UTC, Mavlyan commented on Model/Atol/Client.php
> +    protected function sendGetRequest(string $url, ?int $storeId = null): string
ад авай мы получим токен в методах sendSell и sendRefund, а в эти методы передадим сам токен.
А то передача стора выглядит печально. 
методы - всего лишь обертка над cURL, и по идее должны оставаться чистыми

2021-06-25 15:09 UTC, Mavlyan commented on Model/Atol/Request.php
> +    public function getStoreId(): ?int
а что если ExternalId будет генерится каким-то другим методом?

2021-06-25 15:09 UTC, Mavlyan commented on Model/Processor/Send.php
> +            $storeId = $this->invoiceRepository->get($invoice->getEntityId());
?

2021-06-25 15:09 UTC, Mavlyan commented on Model/Queue/Consumer/RefundConsumer.php
> +     * @throws \Magento\Framework\Exception\LocalizedException|\Magento\Framework\Exception\NoSuchEntityException
please use use

2021-06-25 15:09 UTC, Mavlyan commented on Model/Queue/Consumer/SellConsumer.php
> +            $storeId = $this->requestHelper->getEntityByRequest($request)->getStoreId();
а как же $request->getStoreId ?

2021-06-25 15:14 UTC, alextorini commented on Console/UpdateStatus.php
> +                foreach ($uuids as $uuid) {
Там дальше везде так или иначе по достается entity и из него берётся storeId

2021-06-25 15:20 UTC, alextorini commented on Model/Queue/Consumer/RefundConsumer.php
> +     * @throws \Magento\Framework\Exception\LocalizedException|\Magento\Framework\Exception\NoSuchEntityException
Мне почему-то казалось, что в пхп доках правильнее полный путь всегда указывать, даже при наличии use. Это не так?

2021-06-29 09:56 UTC, alextorini commented on Helper/Transaction.php
> +                    '%s.%s IS NULL',
Так тут так и было, в комменты выше написано:
// если используются очереди, получаем только те транзации, для которых нет активных
// заданий на обновление статуса

2021-06-29 13:18 UTC, Mavlyan requested changes

2021-06-29 13:18 UTC, Mavlyan commented on Crontab/Update.php
> +        Proxy $transactionHelper,
просто надпись Proxy выглядит не очень. Что за прокси? Сделай ей хотя бы элиас TransactionHelper

2021-06-29 13:18 UTC, Mavlyan commented on Model/Processor/Send.php
> +        $this->invoiceRepository = $invoiceRepository;
Ыыыы

2021-06-29 13:18 UTC, Mavlyan commented on Model/Queue/Consumer/RefundConsumer.php
> +            $storeId = $this->requestHelper->getEntityByRequest($request)->getStoreId();
а зачем? 
неужели в реквесте нет storeId ?

2021-06-29 13:18 UTC, Mavlyan commented on Model/Processor/Send.php
> +        $storeId = $this->requestHelper->getEntityByRequest($request)->getStoreId();
а в реквесте нет storeId ? 
в других методах в этом классе такая же история. Кроме метода `proceedResellRefund`. Там ты берешь из реквеста

2021-06-29 13:18 UTC, Mavlyan commented on Model/Queue/Consumer/ResellConsumer.php
> +            $storeId = $this->requestHelper->getEntityByRequest($request)->getStoreId();
ы 2.0

2021-06-29 13:39 UTC, Mavlyan approved these changes

2021-06-30 11:59 UTC, Daseraf commented on Console/UpdateStatus.php
> +        if ($param === self::RUN_ALL_PARAM) {
guard clause

2021-06-30 11:59 UTC, Daseraf commented on Crontab/Update.php
> +        foreach ($this->storeRepository->getList() as $store) {
Перенести в отдельную модель, ввиду наличия аналогичного кода в консольном классе.

2021-06-30 11:59 UTC, Daseraf commented on Helper/Data.php
>              throw new Exception('No login specified.');
LocalizedException

2021-06-30 11:59 UTC, Daseraf commented on Helper/Data.php
>              throw new Exception('No password specified.');
LocalizedException

2021-06-30 11:59 UTC, Daseraf commented on Model/Atol/Client.php
> +     * @throws \Exception
Вернуть верные исключения

2021-07-01 13:55 UTC, Mavlyan requested changes

2021-07-01 13:55 UTC, Mavlyan commented on Helper/Transaction.php
> +                ->joinLeft(
АЛАРМ! 

Одинаковый джоин тусуется и в IF и в ELSE.
Можно перед или после IFа сделать что-то типа if($storeId) и туда вынести джоин. Иначе он может быть NULL, а мы такие что-то джоиним!

2021-07-01 15:32 UTC, Mavlyan approved these changes

2021-07-05 12:49 UTC, luckyraul commented
revert 2020, create new PR for it

2021-07-05 13:37 UTC, luckyraul commented on Model/Atol/Request.php
> +        return $this->storeId;
force to int or null. Prevent string

2021-07-05 13:37 UTC, luckyraul commented on Console/UpdateStatus.php
> +        State $state,
Why we need State?

2021-07-05 13:37 UTC, luckyraul commented on Console/UpdateStatus.php
> +use Mygento\Kkm\Helper\Transaction\Proxy as TransactionHelper;
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/proxies.html#proxies-are-generated-code

2021-07-05 13:37 UTC, luckyraul commented on Console/UpdateStatus.php
> +        if ($param !== self::RUN_ALL_PARAM) {
rename $param

2021-07-05 13:37 UTC, luckyraul commented on Helper/Transaction.php
> +            ->joinLeft(
just join

2021-07-05 13:37 UTC, luckyraul commented on Helper/Transaction.php
> +        $transactions->getSelect()
no guarantee for collection
use collectionProcessor

2021-07-05 13:37 UTC, luckyraul commented on Helper/Transaction.php
> +        if ($this->kkmHelper->isMessageQueueEnabled($storeId)) {
move to collectionProcessor

2021-07-05 13:37 UTC, luckyraul commented on Model/Atol/Client.php
> +     * @throws \Exception
*@throws \Exception

2021-07-05 13:48 UTC, luckyraul requested changes

2021-07-05 13:48 UTC, luckyraul commented on Crontab/Update.php
> +        foreach ($this->storeRepository->getList() as $store) {
extract to  a new method

2021-07-15 10:29 UTC, Mavlyan approved these changes

2021-07-15 10:42 UTC, alextorini commented on Model/Atol/Request.php
> +        return $this->storeId;
: ?int это и сделает  (если не включены strict_types)

2021-07-16 10:28 UTC, luckyraul commented on Helper/TransactionAttempt.php
> +            ->setStoreId($entity->getStoreId())
Should we update this field to entity store id?

2021-07-19 15:02 UTC, alextorini commented on Helper/TransactionAttempt.php
> +            ->setStoreId($entity->getStoreId())
Я обновил филтьтры, через которые мы получаем  уиды. Теперь мы не используем update аттемпты для получения стора, так что по идее теперь не важно что тут сеттится .

2021-07-19 16:23 UTC, luckyraul commented on Model/Transaction/Api/SearchCriteria/FilterProcessor/StoreFilter.php
> +            ->reset('columns')
zend constant

2021-07-19 16:23 UTC, luckyraul commented on Model/Transaction/Api/SearchCriteria/FilterProcessor/StoreFilter.php
> +                ''
array or empty string?

2021-07-19 16:24 UTC, luckyraul commented on Model/Transaction/Api/SearchCriteria/FilterProcessor/UpdateTimeoutFilter.php
> +            ->reset('columns')
constant

2021-07-20 07:46 UTC, alextorini commented on Model/Transaction/Api/SearchCriteria/FilterProcessor/StoreFilter.php
> +                ''
Там вроде и так и так можно

2021-07-20 09:58 UTC, merged