LIS-15
mygento/kkm pull request #77
Opened 2021-07-06 11:59 UTC by Basharabum

- Save error types and codes to the attempts table
- Add grid with kkm transaction attempts

2021-07-09 14:57 UTC, Mavlyan requested changes

2021-07-09 14:57 UTC, Mavlyan commented on Helper/Data.php
> +     * @return string
string|bool

2021-07-09 14:57 UTC, Mavlyan commented on Helper/Error.php
> +            if (!$failStatus) {
Если у тебя статус не задан, то в заказы не будут писаться комментарии что происходит с их чеками. А это неверно. Комментарий должен быть записан. Статус просто не меняется

2021-07-09 14:57 UTC, Mavlyan commented on Model/Atol/Vendor.php
> +            $attempt->setErrorType(ErrorType::UNDEFINED);
Смари: 

насколько я тут всё приавльно прочитал - CreateDocumentFailedException создан таким образом, что в нём есть $response. Насколько я помню, это ошибка когда мы всё отправили, но что-то оказалось невалидным. Типа там суммы не сошлись. То есть на уровне сервера это 200 ОК, но это ошибка. Што из етого следует:

1. Было бы неплохо привести кастомные эксепшыны к одному виду - или интерфейсу. AuthorizationException  и CreateDocumentFailedException чем-то похожи. Один из них содержит весь респонс, а второй только код и тип ошибки. Если это возможно (посмотри плз) - то пускай обои содержат или респонс или только код и тип ошибки. 

2. В этом месте у тебя $response всегда будет NULL. `CreateDocumentFailedException` падает при вызове метода из класса Клиент (см.выше строка 685). А следовательно переменная $response не будет проинициализирована. Однако этот эксепшын `CreateDocumentFailedException` сам содержит весь респонс. И логично брать респонс прямо из эксепшна этого типа. 

Похожая история и с VendorNonFatalErrorException:

![image](https://user-images.githubusercontent.com/8666986/125095871-47af5800-e0dd-11eb-8515-eb8f974c27b1.png)

2021-07-09 14:57 UTC, Mavlyan commented on Model/TransactionAttempt.php
> +     * @return string|null
а int может быть ?  в новых сеттерах и геттерах проверь

2021-07-09 15:32 UTC, Mavlyan commented
Версию композера надо увеличить

2021-07-22 15:14 UTC, luckyraul commented on Helper/Data.php
> +        return $this->getConfig('general/fail_status') ?: false;
remove ?: false

2021-07-22 15:39 UTC, merged