LIS-12 - Fix attempt grid filtering
mygento/kkm pull request #87
Opened 2021-09-02 12:03 UTC by Basharabum

2021-10-20 14:32 UTC, Basharabum commented
SELECT `main_table`.*,
       (CONCAT(order_id, "_", operation, "_", sales_entity_id) IN
        ('88_3_5', '115_1_6', '115_3_6', '55317913_3_55115806', '55317916_1_55113979', '55317916_3_55113979',
         '55317922_1_55114270', '55317922_3_55114270', '55317928_1_55115809', '55317928_3_55115809',
         '55317931_1_55114267', '55317931_3_55114267')) AS `is_closed`
FROM `mygento_kkm_transaction_attempt` AS `main_table`

2021-12-03 16:53 UTC, Mavlyan commented
со словом Cheque обнаружилась проблема, что это одно т тьо же, что и Check. 
По-хорошему сущность надо бы именовать Receipt. 
Об этом стоит подумать - может эжто и не надо нигде менять

2021-12-03 16:54 UTC, Mavlyan requested changes

2021-12-03 16:54 UTC, Mavlyan commented on Controller/Adminhtml/Cheque/MassResend.php
> +                $this->resender->resend(
Массовая отправка должна быть асинхронной

2021-12-03 16:54 UTC, Mavlyan commented on Helper/TransactionAttempt.php
> +    public function markTransactionAttempt(
зачем multiline

2021-12-03 16:54 UTC, Mavlyan commented on Helper/TransactionAttempt.php
> +    public function markTransactionAttempt(
updateStatusByTransaction()

2021-12-03 16:54 UTC, Mavlyan commented on Helper/TransactionAttempt.php
> +        $entity,
multiline

2021-12-03 16:54 UTC, Mavlyan commented on Model/Atol/Vendor.php
>              //Mark attempt as Sent
plural form

2021-12-03 16:54 UTC, Mavlyan commented on Model/Atol/Vendor.php
> +            $this->attemptHelper->updateStatus(
multi line

2021-12-03 16:54 UTC, Mavlyan commented on Model/Atol/Vendor.php
> +            $this->attemptHelper->updateStatus(
5 дублей этого кода заменить на 1 строку

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +    private const ATTEMT_TABLE_ALIAS = 'transaction_attempt';
буква пропущена

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +        $union = $this->getConnection()->select()->union(
\Magento\Framework\DB\Sql\UnionExpression

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +        $isClosedExpression = $this->expressionFactory->create(['expression' => 'IF((' . self::ATTEMT_TABLE_ALIAS . '.operation = 1
1. Я предпочитаю читаемость сложного кода.
2. константу с таблицей прдлгю заменить на приватное поле класса
3. Сделать БОЛЕЕ читаемой строку
4. цифры не должны быть цифрами, а константами || переменными (чтобы интерпретатор их резолвил внутри строки) \Mygento\Kkm\Api\Data\RequestInterface

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +        $isClosedExpression = $this->expressionFactory->create(['expression' => 'IF(' . self::ATTEMT_TABLE_ALIAS . '.operation = 2 AND ' . self::ATTEMT_TABLE_ALIAS . '.status = 4, 1, 0)',
слишком длинная строка

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +                'sales_entity_type' => $this->expressionFactory->create(['expression' => "'${entityType}'"]),
![image](https://user-images.githubusercontent.com/8666986/144634675-5552ec31-d700-45d4-896e-53d3590ad6c8.png)


попробовать сделать вотак

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +            [self::SALES_ORDER_TABLE_ALIAS => $orderTable],
мне кажется alias тут лишний
можно передать просто строку 

```joinLeft($orderTable, ...```

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +            [self::ENTITY_LAST_ATTEMPT_ALIAS => $this->buildEntityLastAttemptSelect()],
поскольку константа self::ENTITY_LAST_ATTEMPT_ALIAS приватная и испольуется только в этом методе - предлагаю сделать её переменной и использовать внутри строки в двойных кавычках

2021-12-03 16:54 UTC, Mavlyan commented on Model/ResourceModel/TransactionAttempt/Grid/Collection.php
> +        string $model = 'Magento\Framework\View\Element\UiComponent\DataProvider\Document',
???

2021-12-03 16:54 UTC, Mavlyan commented on README.md
> +  * переводит попытку отправки в статус done при закрытии транзакции без ошибок.
obsolette

2021-12-03 16:54 UTC, Mavlyan commented on Ui/Component/Listing/Column/ChequeStatus/Actions.php
> +            if (!$item['is_closed']) {
Проверки недостаточно. Т.к. если транзакция в статусе WAIT, то кнопка resend отобразится и отправится. Но это неправильно! :-1: 

Поэтому логику проверки на ресенд необходимо вынести в `Resender` - чтобы избежать повторной отправки.

2021-12-03 16:54 UTC, Mavlyan commented on Ui/Component/Listing/Column/ChequeStatus/Actions.php
> +                $actions['resend'] = [
ACL не проверяется. Если ент прав - не надо показывать кнопку.

идея:
 * сделать ValidatorPool (\Magento\Ui\DataProvider\Modifier\Pool)
 * два валидатора: 
   *  один в di.xml указать - проверка на статус транзакции
   *  второй в adminhtml/di.xml  - проверка ACL

2021-12-03 16:54 UTC, Mavlyan commented on Ui/Component/Listing/Column/ChequeStatus/Actions.php
> +            ? $this->urlBuilder->getUrl(
multiline

2021-12-03 16:54 UTC, Mavlyan commented on etc/acl.xml
> +
пустая строка

2021-12-03 16:54 UTC, Mavlyan commented on etc/acl.xml
> +                    <resource id="Mygento_Kkm::chequestatus" title="Kkm Cheque Status" translate="title" sortOrder="140"/>
Назови как-то иначе, потому жесть. и id и title

2021-12-07 10:22 UTC, Basharabum commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +        $union = $this->getConnection()->select()->union(
нашел примеры использования только через new \Magento\Framework\DB\Sql\UnionExpression.
Через expressionFactory получить такую реализацию не получилось, т.к через create метод этой фабрики нельзя выбрать конретную реализацию.
А $this->getConnection()->select()->union выглядит лучше, чем new \Magento\Framework\DB\Sql\UnionExpression

2021-12-07 11:40 UTC, Basharabum commented on Model/ResourceModel/ChequeStatus/Grid/Collection.php
> +                'sales_entity_type' => $this->expressionFactory->create(['expression' => "'${entityType}'"]),
Не получилось. Создает строку вида имя_таблицы.`invoice`

2021-12-07 11:41 UTC, Basharabum commented on Ui/Component/Listing/Column/ChequeStatus/Actions.php
> +            if (!$item['is_closed']) {
Добавил валидацию в ресендер вызовом Mygento\Kkm\Model\Resend\ValidatorInterface

2021-12-07 11:42 UTC, Basharabum commented on Ui/Component/Listing/Column/ChequeStatus/Actions.php
> +                $actions['resend'] = [
добавил валидатор пулл

2021-12-08 14:59 UTC, Mavlyan requested changes

2021-12-08 14:59 UTC, Mavlyan commented on Model/Resend/ValidatorComposite.php
> +     * @throws ResendAvailabilityException
имя эксепшна мне кажца должно отражать уже суть ошибки. типа как NullPointerException, AclNotFoundException, BadAttributeValueException. 
А корневые могут иметь общие имена типа LocalizedException.
Поэтому я бы переименовал в `ResendUnavailableException`

2021-12-08 14:59 UTC, Mavlyan commented on Model/Atol/Vendor.php
> +            //Mark attempt with operation type == update as sent
:+1: :1st_place_medal:

2021-12-08 14:59 UTC, Mavlyan commented on etc/di.xml
> +    <type name="Mygento\Kkm\Model\Resend\ValidatorComposite">
а в чем смысл в двух разных местах передавать аргументы в ValidatorComposite ?

2021-12-08 15:07 UTC, Mavlyan commented on etc/acl.xml
> +                    <resource id="Mygento_Kkm::transactionattempt" title="Kkm Transaction Attempt" translate="title" sortOrder="130"/>
Названия решил не менять?

2021-12-08 15:33 UTC, Basharabum commented on etc/acl.xml
> +                    <resource id="Mygento_Kkm::transactionattempt" title="Kkm Transaction Attempt" translate="title" sortOrder="130"/>
Переименовал Mygento_Kkm::chequestatus в Mygento_Kkm::chequestatus_grid.
Глобально переименовывать cheque в receipt не стал

2021-12-08 15:47 UTC, Mavlyan commented on etc/acl.xml
> +                    <resource id="Mygento_Kkm::transactionattempt" title="Kkm Transaction Attempt" translate="title" sortOrder="130"/>
Может не закомитил? Я не вижу `Mygento_Kkm::chequestatus_grid`
title тоже надо переименовать понятнее дабы на странице с ролями путаницы избежать.

2021-12-08 15:50 UTC, Mavlyan approved these changes

2021-12-09 10:13 UTC, luckyraul approved these changes

2021-12-09 10:13 UTC, merged