Chekonline. Added receipt link to order comment (ASUS-194)
mygento/kkm pull request #88
Opened 2021-11-30 17:59 UTC by odahviiiing

2021-12-02 09:49 UTC, Mavlyan requested changes

2021-12-02 09:49 UTC, Mavlyan commented on etc/adminhtml/system.xml
> +                <field id="test_ofd_url" translate="label" type="text" sortOrder="111" showInDefault="1" showInWebsite="1" showInStore="1">
Думаю, что значения по умолчанию для обоих настроек стоит добавить в config.xml.

2021-12-06 07:37 UTC, odahviiiing commented on etc/adminhtml/system.xml
> +                <field id="test_ofd_url" translate="label" type="text" sortOrder="111" showInDefault="1" showInWebsite="1" showInStore="1">
Добавил

2021-12-06 11:29 UTC, Mavlyan approved these changes

2021-12-09 09:37 UTC, luckyraul approved these changes

2021-12-09 09:39 UTC, merged